# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 216)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.degree = QtWidgets.QComboBox(Form)
        self.degree.setObjectName("degree")
        self.degree.addItem("")
        self.degree.addItem("")
        self.degree.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.degree)
        self.form = QtWidgets.QComboBox(Form)
        self.form.setObjectName("form")
        self.form.addItem("")
        self.form.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.form)
        self.price = QtWidgets.QSpinBox(Form)
        self.price.setMaximum(999999999)
        self.price.setObjectName("price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price)
        self.volume = QtWidgets.QSpinBox(Form)
        self.volume.setMaximum(999999999)
        self.volume.setObjectName("volume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volume)
        self.taste = QtWidgets.QLineEdit(Form)
        self.taste.setObjectName("taste")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.taste)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название сорта"))
        self.label_2.setText(_translate("Form", "Степень обжарки"))
        self.label_3.setText(_translate("Form", "Молотый/в зёрнах"))
        self.label_4.setText(_translate("Form", "Описание вкуса"))
        self.label_5.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Объем упаковки"))
        self.degree.setItemText(0, _translate("Form", "светлая"))
        self.degree.setItemText(1, _translate("Form", "средняя"))
        self.degree.setItemText(2, _translate("Form", "темная"))
        self.form.setItemText(0, _translate("Form", "молотый"))
        self.form.setItemText(1, _translate("Form", "в зёрнах"))
        self.pushButton.setText(_translate("Form", "Добавить"))
